/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ArrayCode1;
import javax.swing.*;
public class App {
   

    public static void main(String[] args) {
    final int NUM_STUDENTS = 10; // constant for the number of students
        int[] marks = new int[NUM_STUDENTS]; // array to store the student marks
        String input; // to hold the user's input
        StringBuilder results = new StringBuilder("Student Marks:\n"); // to compile results for display

        // Loop to collect marks
        for (int i = 0; i < marks.length; i++) {
            input = JOptionPane.showInputDialog(null, "Enter marks for Student " + (i + 1)  );

            // Validate input is an integer
          
                marks[i] = Integer.parseInt(input);
         
        }
        // Append marks to the results
        for (int i = 0; i < marks.length; i++) {
            results.append("Student ").append(i + 1).append(": ").append(marks[i]).append("\n");
        }

        // Display the results
        JOptionPane.showMessageDialog(null, results.toString(), "Student Marks", JOptionPane.INFORMATION_MESSAGE);
    }
}